python3 larval/train_script.py \
    --data /Users/mraoaakash/Documents/research/research-zebrafish/Movement/zebrafish_movement/larval/data.yaml  \
    --epochs 25  \
    --imgsz 1920  \
    --name Larval-Run  \
    --batch 8  \
    --save_period 2 \
    --device mps,  \
    --rect True  \
    --workers 0 \